name: Generate ASCII Art
on: push
jobs:
    generate-ascii-job: 
        runs-on: ubuntu-latest
        steps: 
        -   name: Checkout
            uses: actions/checkout@v4
        -   name: Install Cowsay
            run: sudo apt-get install -y cowsay
        -   name: Execute Cowsay command
            run: cowsay "hello world"
                